export enum AllRoutes {
  Home = "Home",
  Profile = "Profile",
  Order = "Order",
  Shop = "Shop",
  Search = "Search",
  Offer = "Offer",
  More = "More",
  Cart = "Cart",
  Categories = "Categories",
  PopularDeals = "PopularDeals",
  AtDiscount = "AtDiscount",
  Category = "Category",
  Product = "Product",
  SignIn = "SignIn",
  SignUp = "SignUp",
}
